kind=defined
names=range_length
visibility=public

--- range_length -> Integer|nil

Content-Range: ヘッダフィールドの表している長さを整数で返します。

ヘッダが設定されていない場合には nil を返します。

@raise Net::HTTPHeaderSyntaxError Content-Range: ヘッダフィールド
                                  の値が不正である場合に
                                  発生します。
                                  
