kind=defined
names=proppatch
visibility=public

--- proppatch(path, body, initheader = nil) -> Net::HTTPResponse
サーバの path に PROPPATCH リクエストを
ヘッダを initheader, ボディを body として送ります。

レスポンスを [[c:Net::HTTPResponse]] のオブジェクト
で返します。

@param path リクエストを送るパスを文字列で与えます。
@param body リクエストのボディを文字列で与えます。
@param initheader リクエストのヘッダを「文字列=>文字列」の
                  ハッシュで与えます。

@see [[c:Net::HTTP::Proppatch]]

