kind=defined
names=proxy_port,proxyport
visibility=public

--- proxy_port -> Integer|nil
--- proxyport -> Integer|nil

プロクシ経由で接続する HTTP オブジェクトならプロクシのポート番号
を返します。

そうでないなら nil を返します。

proxyport は時代遅れのメソッドです。
@see [[m:Net::HTTP.Proxy]]
