kind=defined
names=set_debug_output
visibility=public

--- set_debug_output(io) -> ()

デバッグ出力の出力先を指定します。
このメソッドは深刻なセキュリティホールの原因
になるため、デバッグ以外では決して使わないでください。

io に nil を指定するとデバッグ出力を止めます。

@param io 出力先を指定します。このオブジェクトは 
          メソッド << を持っている必要があります。

  http.set_debug_output($stderr)


