kind=defined
names=start
visibility=public

--- start -> self
--- start {|http| .... } -> object

TCP コネクションを張り、HTTP セッションを開始します。
すでにセッションが開始していたら例外 IOError を発生します。

ブロックを与えた場合には自分自身をそのブロックに
渡し、ブロックが終わったときに接続を閉じます。このときは
ブロックの値を返り値とします。

ブロックを与えなかった場合には自分自身を返します。
利用後にはこのオブジェクトを [[m:Net::HTTP#finish]] してください。

@raise IOError すでにセッションが開始していた場合に発生します。

