kind=defined
names=proxy_address
visibility=public

--- proxy_address -> String|nil
自身が ([[m:Net::HTTP.Proxy]] によって作成された) 
プロクシ用のクラスならばプロクシのアドレスを返します。

そうでなければ nil を返します。

@see [[m:Net::HTTP.Proxy]]

