kind=defined
names=new
visibility=public

--- new(path, initheader = nil) -> Net::HTTPRequest
HTTP リクエストオブジェクトを生成します。

initheader でリクエストヘッダを指定することができます。
{ヘッダフィールド名(文字列)=>その中身(文字列)} という
[[c:Hash]] を用います。

@param path リクエストする path を文字列で与えます。
@param initheader リクエストヘッダをハッシュで指定します。





