kind=defined
names=+@,ptr
visibility=public

--- ptr   -> DL::CPtr
--- +@    -> DL::CPtr

自身の指す値を CPtr にして返します。
自身の指す値はポインタであると仮定します。
C 言語におけるポインタのポインタに対する間接参照 *p と同じです。 

この返り値には、free 関数がセットされていません。

例:

 require 'dl/import'
 
 s = 'abc'
 cptr = DL::CPtr[s]
 cref = cptr.ref
 p cref.to_s(4).unpack('l*')[0]  #=> 136121648
 p cptr.to_i                     #=> 136121648
 p cref.ptr.to_s                 #=> "abc"

