;;; popwin.el
(require 'popwin)

(setq popwin:special-display-config nil)
(setq display-buffer-function 'popwin:display-buffer)

(add-to-list 'popwin:special-display-config '("*Help*"))
(add-to-list 'popwin:special-display-config '("*Completions*" :noselect t))
(add-to-list 'popwin:special-display-config '("*compilation*" :noselect t))
(add-to-list 'popwin:special-display-config '("*Compile-Log*" :noselect t))
(add-to-list 'popwin:special-display-config '("*Occur*" :noselect t))
(add-to-list 'popwin:special-display-config '("*Backtrace*"))
(add-to-list 'popwin:special-display-config '("*Remember*" :stick t))
(add-to-list 'popwin:special-display-config '("*Org Agenda*"))
(add-to-list 'popwin:special-display-config '("*sdic*" :noselect))
(add-to-list 'popwin:special-display-config '("*Apropos*"))
(add-to-list 'popwin:special-display-config '("*Warnings*"))
(add-to-list 'popwin:special-display-config '(" *auto-async-byte-compile*" :noselect))
;; (setq popwin:special-display-config
;;       (append '(("*Backtrace*")
;;                 ("*Remember*" :stick t)
;;                 ("*Org Agenda*")
;;                 ("*sdic*" :noselect)
;;                 ("*Apropos*")
;;                 ("*Warnings*")
;;                 ("compilation")
;;                 (" *auto-async-byte-compile*" :noselect))
;;               popwin:special-display-config))

(define-key dired-mode-map "o" '(lambda ()
                                   (interactive)
                                   (popwin:find-file (dired-get-file-for-visit))))
;; (key-chord-define-global "mn" 'popwin:messages)

(define-key global-map (kbd "C->") popwin:keymap)
;; (defun add-popwin-find-file (dired-get-file-for-visit)
;;   (interactive)
;;   (popwin:find-file (dired-get-file-for-visit)))
;; (define-key dired-mode-map (kbd "o") '(add-popwin-find-file (dired-get-file-for-visit)))
